language: java
jdk:
  - oraclejdk9
branches:
  only:
  - master
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport 
after_success:
  - bash <(curl -s https://codecov.io/bash)
